version: 0.1.1
env:
  - BUILD_MACHINE: "Dynamo_Win_003"
check_changelog_updated_on_pr: false
pipeline_os: "Windows"

build:
    before_scripts:
        - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuildScript.ps1"
    scripts:
        - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\BuildScript.ps1"
    after_scripts:
        - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PostBuildScript.ps1"
    
ci_test:
  before_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\TestSetup.ps1"
  scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\ExecuteParallelTest.ps1"
  test_report_dir: TestResults
  test_report_files:
    -
      file_name: "TestResult-AnnotationViewModelTests.xml"
      format: nunit
    -
      file_name: "TestResult-CodeCompletionTests.xml"
      format: nunit
      
notifications:
  slack: dynamo-team:XCFz6s0hJl3QOYyRRlXdGhRg