version: 0.1.1
env:
  - BUILD_MACHINE: "Dynamo_Win_003"
  - SLACK_QUANTUM_BUILD_CHANNEL : "#quantum-build"
  - SLACK_QUANTUM_BUILD_TOKEN : "J5mMX9m33xrxZoy1NiBJ27qb"
  
check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification : true

build:
    before_scripts:
        - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuildScript.ps1"
    scripts:
        - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\BuildScript.ps1"
    after_scripts:
        - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PostBuildScript.ps1"
    
ci_test:
  before_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\TestSetup.ps1"
  scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\ExecuteParallelTest.ps1"
  test_report_dir: TestResults
  test_report_files:
    -
      file_name: "TestResult-AnnotationViewModelTests.xml"
      format: nunit
    -
      file_name: "TestResult-CodeCompletionTests.xml"
      format: nunit  
    -
      file_name: "TestResult-AnalysisTests.xml"
      format: nunit
