version: 0.1.1
env:
  - BUILD_MACHINE: "Dynamo_Win_003"
check_changelog_updated_on_pr: false
pipeline_os: "Windows"

build:
  scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\BuildScripts.ps1"
    
ci_test:
  before_scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\TestSetup.ps1"
  scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\ParallelTest.ps1 -path C:\\Jenkins\\workspace\\Dynamo\\Dynamo\\DYN-1822\\src\\Tools\\TransformXMLToCSVTool\\Result\\textFileWithFiltersFastTests.txt"
  test_report_dir: TestResults
